apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo-service.fullname" . }}
  labels:
    {{- include "demo-service.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "demo-service.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "demo-service.labels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: http 
      path: /actuator/prometheus
