apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      otus.app/name: demo-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        otus.app/name: demo-service
    spec:
      containers:
        - name: demo-serivce
          image: auwerk/demo-service:v1.0.4
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: APP_DB_URL
              value: jdbc:postgresql://postgresql-dev.default.svc.cluster.local:5432/app_db
            - name: APP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: USERNAME
                  optional: false
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: PASSWORD
                  optional: false
          ports:
            - name: web
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: web
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: web
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: web
            failureThreshold: 30
            periodSeconds: 10
