apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: dbinit
        image: auwerk/demo-service:v1.0.7
        env:
          - name: APP_DB_URL
            valueFrom:
              configMapKeyRef:
                name: appconfig
                key: DB_URL
          - name: APP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: USERNAME
                optional: false
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: PASSWORD
                optional: false
        command: ['java','-jar','/opt/app/app.jar','--spring.profiles.active=init']
      restartPolicy: Never
  backoffLimit: 4
