apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
      - name: dbinit
        image: auwerk/demo-service:v1.0.4
        env:
          - name: APP_DB_URL
            value: jdbc:postgresql://postgresql-dev.default.svc.cluster.local:5432/app_db
          - name: APP_DB_USERNAME
            value: app1
          - name: APP_DB_PASSWORD
            value: app1_password
        command: ['java','-jar','/opt/app/app.jar','--spring.profiles.active=init']
      restartPolicy: Never
  backoffLimit: 4
