apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-service.fullname" . }}
data:
  DB_URL: "jdbc:postgresql://{{ .Values.db.hostName }}.{{ .Values.db.namespace }}.svc.cluster.local:5432/{{ .Values.db.name }}"
 
