{
 "title": "demo-service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{path=\"/user/(.*)/*\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{path=\"/user/(.*)/*\",status=\"500\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/user/(.*)/*\"}[2m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/user/(.*)/*\"}[2m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/user/(.*)/*\"}[2m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/user/(.*)/*\"}[2m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "By API method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GET /user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/user\",method=\"GET\"}[2m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"500\",method=\"GET\",uri=\"/user\"}[2m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "GET /user latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  {
   "title": "GET /user/{id}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{uri=\"/user/{id}\",method=\"GET\"}[2m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"500\",method=\"GET\",uri=\"/user/{id}\"}[2m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "GET /user/{id} latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  {
   "title": "POST /user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{uri=\"/user\",method=\"POST\"}[2m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"500\",method=\"POST\",uri=\"/user\"}[2m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "POST /user latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\",uri=\"/user\"}[2m]))) * 1000",
     "legendFormat": "q=0.99"
    }
   ]
  },
  {
   "title": "DELETE /user/{id}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{uri=\"/user/{id}\",method=\"DELETE\"}[2m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{status=\"500\",method=\"DELETE\",uri=\"/user/{id}\"}[2m])",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "DELETE /user/{id} latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\",uri=\"/user/{id}\"}[2m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"otus\"}[5m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"otus\"}[5m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}