{{- $fullName := include "demo-service.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullName }}-user"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /user/(.*)/*
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
