management:
  endpoint:
    health:
      probes:
        enabled: true
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate