management:
  endpoint:
    health:
      probes:
        enabled: true
spring:
  main:
    banner-mode: off
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate