management:
  endpoint:
    health:
      probes:
        enabled: true
spring:
  datasource:
    url: jdbc:postgresql://postgresql-dev.default.svc.cluster.local:5432/app_db
    username: app1
    password: app1_password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate